### ISSUE TITLE
TASK 1: Login Functionality + some basic styling

### ISSUE THREAD

**Issue by amygeorge** [kaavyalakshmanan/tele-vet#10]
Create a login page that meetings project progress 2 requirements

**Comment by kaavyalakshmanan** [comment]
Minimal Requirements:

COMPONENT 1: LogIn.js
COMPONENT 2: VetLogIn.js
COMPONENT 3: PetLogIn.js
COMPONENT 4: SignUp.js
COMPONENT 5: VetSignUp.js
COMPONENT 6: PetSignUp.js

- [x] **Home.js** which will have “LogIn” & “SignUp” links in navbar that redirect to separate components - **VetLogIn.js**,  **PetLogIn.js**, **VetSignUp.js**& **PetSignUp.js**
- [x] **LogIn.js** is dropdown which will redirect to **VetLogIn.js** & **PetLogIn.js**-  which will prompt user to enter their username and password. When they hit “Submit” nothing happens
- [x] **SignUp.js** is dropdown which will redirect to **VetSignUp.js** & **PetSignUp.js**-  which will prompt user registration form. When they hit “Submit” nothing happens
- [ ] Add validation to LogIn forms (STRETCH GOAL)
- [ ] Add validation to Registration forms (STRETCH GOAL)
- [ ] Vet reg form: option to upload certificate (STRETCH GOAL)
