### ISSUE TITLE
TASK 3: Database Set-Up

### ISSUE THREAD

**Issue by amygeorge** [kaavyalakshmanan/tele-vet#11]
Minimal Requirements:

- [ ] Create the db with the 3 entities (Pet, Pet Owners Vet…. Additional info on README)
- [ ] Look into how this interacts with front-end log-in so when user logs in as Pet Owner, it populates the appropriate db… etc
- [ ] Finish database diagram

**Comment by Franco-yvr** [comment]
Task#1: Offer option for user to sign in as vet or as pet.

Task#2:
