### ISSUE TITLE
AMY - GOOGLE MAPS

### ISSUE THREAD

**Issue by kaavyalakshmanan** [kaavyalakshmanan/tele-vet#37]
- [x] RESTful APIs working with Maps

- [x] Pull from Google API to populate with data

- [x] Get user’s current location

- [x] Filter by ‘vets near you’

- [x] Map grid —> fix overlapping issue (flex properly)

- [ ] Filter by ratings (STRETCH)

- [ ] Updating new vets 

- [x] Make database, create basic collections (vets, users, etc), get everyone credentials so can run on terminal

**Comment by amygeorge** [comment]
See if this can help fix user location issues next week: https://medium.com/better-programming/the-best-practice-with-google-place-autocomplete-api-on-react-939211e8b4ce
