### ISSUE TITLE
TASK 2: Google Maps integration + some basic styling

### ISSUE THREAD

**Issue by amygeorge** [kaavyalakshmanan/tele-vet#9]
Initial rendering of google maps - use to meet component requirements

**Comment by kaavyalakshmanan** [comment]
Check out https://bcpetregistry.ca/find-a-veterinarian/ for inspo.

Minimal Requirements:
- [x] Create a NEW tab on **Home.js** called **Maps** which redirects to **Maps.js** and shows user Google maps view.
- [x] Default to showing map of Lower Mainland.
- [x] Add markers to the map to indicate location of vets
- [ ] When user clicks on marker, it shows a view with info about the clinic
- [ ] Add a sidebar with info about the vets
- [ ] Add a filter and search bar at the top (it won’t do anything right now)
